name: Bloodline Welcome Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLAN_ID: ${{ secrets.CLAN_ID }}
        run: node bot.js

      - name: Guardar memoria del bot
        run: |
          git config --global user.name "Bloodline Bot"
          git config --global user.email "bot@github.com"
          git add welcomed_users.json
          git commit -m "Update memory" || echo "No changes"
          git push
