name: Bloodline Welcome Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLAN_ID: ${{ secrets.CLAN_ID }}
        run: node bot.js
